[package]
name = "netlink-packet-amnezia-wireguard"
version = "0.3.0"
edition = "2021"
homepage = "https://github.com/frkn-dev/netlink-packet-amnezia-wireguard"
repository = "https://github.com/frkn-dev/netlink-packet-amnezia-wireguard"
keywords = ["wireguard", "netlink", "linux", "amnezia"]
license = "MIT"
readme = "README.md"
description = "Amnezia WireGuard generic netlink packet definitions"

[dependencies]
libc = "0.2.98"
log = "0.4.14"
netlink-packet-generic = { version = "0.5" }
netlink-packet-core = { version = "0.9" }
bitflags = "2"

[dev-dependencies]
base64 = "0.22.1"
env_logger = "0.11.10"
futures = "0.3.16"
getrandom = "0.4.2"
pretty_assertions = "1.4.1"

[target.'cfg(target_os = "linux")'.dev-dependencies]
netlink-proto = { version = "0.13" }
genetlink = { version = "0.3" }
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread"] }
